version: "3.8"

services:
    mariadb-service:
        image: mariadb:10.8.2
        container_name: mariadb-eleclist-container
        restart: on-failure
        ports:
            - "3305:3305"
        volumes:
            - db-data-eleclist:/var/lib/mysql
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
        networks:
            - symfony

    phpmyadmin-service:
        image: phpmyadmin
        container_name: phpmyadmin-eleclist-container
        restart: on-failure
        depends_on:
            - mariadb-service
        ports:
            - "8070:80"
        environment:
            PMA_HOST: mariadb-service
        networks:
            - symfony

    php74-service:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: php74-eleclist-container
        ports:
            - "8000:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: on-failure
        networks:
            - symfony

    encore:
        image: node:14-alpine
        volumes:
            - .:/app
        ports:
            - "${DEV_SERVER_PORT:-8090}:8090"
        working_dir: /app
        command: [ "yarn", "dev-server", "--host=0.0.0.0" ]

networks:
    symfony:

volumes:
    db-data-eleclist:
