version: "3.8"

services:

    mariadb-service:
        image: mariadb:10.8.2
        container_name: mariadb-eleclist-container
        restart: on-failure
        ports:
            - "3306:3306"
        volumes:
            - db-data-eleclist:/var/lib/mysql
        environment:
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
        networks:
            - symfony

    phpmyadmin-service:
        image: phpmyadmin
        container_name: phpmyadmin-eleclist-container
        restart: on-failure
        depends_on:
            - mariadb-service
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mariadb-service
        networks:
            - symfony

    php74-service:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: php74-eleclist-container
        ports:
            - "8741:80"
        volumes:
            - ./php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: on-failure
        networks:
            - symfony

    composer:
        build:
            context: ./dockerfiles
            dockerfile: composer.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        container_name: composer
        volumes:
            - ./:/var/www
        working_dir: /var/www
        depends_on:
            - php74-service
        user: symfony
        entrypoint: [ 'composer', '--ignore-platform-reqs' ]
        networks:
            - symfony

networks:
    symfony:

volumes:
    db-data-eleclist:
