parameters:
  address_api_data:
    api_url: https://api-adresse.data.gouv.fr/search/csv/
    fields_to_send:
      - numéro de voie
      - libellé de voie
      - complément 1
      - complément 2
      - code postal
      - commune

    fields_to_receive:
      - result_housenumber
      - result_name
      - result_city
      - result_postcode
